import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button, Checkbox, Flex, Heading, IconButton, Input, MenuButton, TagCloseButton } from '@chakra-ui/react'
import Link from 'next/link';
import Navbar from '../components/Navbar';

const LoginPage = ()=>{
  return(

    
    <Flex  height="100vh" alignItems="center" justifyContent="center">
      <Flex direction="column" background="gray.100" p={10} rounded={6} height="475px">
        <Heading textAlign="center" mb={6}>Log in</Heading>
        <Input placeholder="SeuEmail@gmail.com" variant="filled" mb={3} type="email"/>
        <Input placeholder="***********" variant="filled" mb={4} type="password"/>
        <Checkbox defaultChecked mb={6} colorScheme="blue"><Flex fontSize="sm">Mantenha-me Conectado</Flex></Checkbox>
        <Link href='/'>
        <Button colorScheme="teal" mb={4}>Log in</Button>
        </Link>
        <Link href='/cadastro'>
        <Button  colorScheme="blue" mb={6}>Cadastro</Button>
        </Link>
        <Flex alignItems="center" fontSize="sm" justifyContent="center" direction="column">Não tenho cadastro<br/><Flex color="blue.600"><a href='/cadastro'>Cadastrar</a></Flex></Flex>
        
      </Flex>
    </Flex>
  )
}

export default LoginPage
// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Ventura</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
